In [19]:
import seaborn as sns

In [20]:
tips = sns.load_dataset('tips')

In [ ]:
# apply , map 잘써야한다
# applymap                  연습!!

In [10]:
tips.sex.map({'Male':1, 'Female':2}) ## 맵은 시리즈에    딕셔너리, 함수써도된다.   ##브로드캐스트
tips.sex.map(lambda x:1 if x=="Male" else 2)  ## 시리즈에 있는 데이터 하나씩 들어옴
        ## 판다스 데이터랭글링 툴, 가져오고, 프로세싱, 보여주고, 간단하게 보여주는거
    ## 맵 
    ## 엑셀에 비해 판다스 쓰는 이유 속도 빠르다
    ## 맵은 시리즈 + 데이터 프레임에 쓸수 있따.
tips = tips.sex.apply(lambda x:1 if x=="Male" else 2)

In [13]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [16]:
tips.apply(lambda x : x['total_bill']+x['tip'], axis=1)   ## 시리즈에 쓸떄는맵하고 똑가다

0      18.00
1      12.00
2      24.51
3      26.99
4      28.20
       ...
239    34.95
240    29.18
241    24.67
242    19.57
243    21.78
Length: 244, dtype: float64

In [21]:
tips.sex.apply(lambda x:1 if x=="Male" else 2)

0      2
1      1
2      1
3      1
4      2
      ..
239    1
240    2
241    1
242    1
243    2
Name: sex, Length: 244, dtype: category
Categories (2, int64): [1, 2]

In [26]:
tips[['total_bill','tip']].applymap(lambda x:x+1)

     total_bill   tip
0         17.99  2.01
1         11.34  2.66
2         22.01  4.50
3         24.68  4.31
4         25.59  4.61
..          ...   ...
239       30.03  6.92
240       28.18  3.00
241       23.67  3.00
242       18.82  2.75
243       19.78  4.00

[244 rows x 2 columns]

In [27]:
tips['ratio'] = tips.apply(lambda x:x['tip']/x['total_bill'], axis=1) ## 비율 넣어서 새로운 축 추가
                                                                    ## 고수들 map, apply 잘씀 -> 전처리하다보면 익숙해짐
                                                                    ## 빨라서 효율적, 차수 늘리면
                                                                    ## 차원이 커지면 차원의 저주 그만큼 데이터가 필요 데이터없으면 학습이 안됨
                                                                    ## 학습 안되면 왜곡된 결과 데이터 많으면 많을수록 무조건 좋음
                                                                    ## + transform

In [28]:
tips

     total_bill   tip     sex smoker   day    time  size     ratio
0         16.99  1.01  Female     No   Sun  Dinner     2  0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3  0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3  0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2  0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4  0.146808
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[244 rows x 8 columns]